FROM node:18-alpine

WORKDIR /app

# Install bash
RUN apk add --no-cache bash

COPY wait-for-it.sh /wait-for-it.sh

COPY package*.json ./
COPY prisma ./prisma
RUN npm install
RUN npx prisma generate

COPY . .

RUN npm run build

EXPOSE 3000

# Use an environment variable to specify which env file to use
ARG ENV_FILE=.env.docker
ENV ENV_FILE=${ENV_FILE}

# Use the ENV_FILE in the CMD
CMD ["bash", "-c", "/wait-for-it.sh postgres:5432 -- npm run start:with-env"]