FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache bash openssl

COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

COPY package*.json ./
COPY prisma ./prisma
COPY prisma.config.ts ./
RUN npm install
RUN npx prisma generate

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["bash", "-c", "/wait-for-it.sh postgres:5432 -- npx prisma db push && npm run start"]
