services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: daily_coding_challenge
            POSTGRES_USER: daily_coding_challenge
            POSTGRES_PASSWORD: daily_coding_challenge
        ports:
            - "5432:5432"
        volumes:
            - daily_coding_challenge_data:/var/lib/postgresql/data

volumes:
    daily_coding_challenge_data:
