export const judge0Languages = [
    { id: 45, name: "Assembly" },
    { id: 46, name: "Bash" },
    { id: 47, name: "Basic" },
    { id: 104, name: "C" },
    { id: 105, name: "C++" },
    { id: 86, name: "Clojure" },
    { id: 51, name: "C#" },
    { id: 77, name: "COBOL" },
    { id: 55, name: "Common Lisp" },
    { id: 90, name: "Dart" },
    { id: 56, name: "D" },
    { id: 57, name: "Elixir" },
    { id: 58, name: "Erlang" },
    { id: 44, name: "Executable" },
    { id: 87, name: "F#" },
    { id: 59, name: "Fortran" },
    { id: 95, name: "Go" },
    { id: 88, name: "Groovy" },
    { id: 61, name: "Haskell" },
    { id: 96, name: "JavaFX" },
    { id: 91, name: "Java" },
    { id: 102, name: "JavaScript" },
    { id: 78, name: "Kotlin" },
    { id: 64, name: "Lua" },
    { id: 89, name: "Multi-file program" },
    { id: 79, name: "Objective-C" },
    { id: 65, name: "OCaml" },
    { id: 66, name: "Octave" },
    { id: 67, name: "Pascal" },
    { id: 85, name: "Perl" },
    { id: 98, name: "PHP" },
    { id: 43, name: "Plain Text" },
    { id: 69, name: "Prolog" },
    { id: 100, name: "Python" },
    { id: 99, name: "R" },
    { id: 72, name: "Ruby" },
    { id: 73, name: "Rust" },
    { id: 81, name: "Scala" },
    { id: 82, name: "SQL" },
    { id: 83, name: "Swift" },
    { id: 101, name: "TypeScript" },
    { id: 84, name: "Visual Basic.Net" }
]
